version: '3.8'
services:
  db:
    container_name: my-todo-list
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ../../docker-volumes/web-template:/var/lib/postgresql/data